name: Run Postman Collections

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Check for hardcoded endpoints
        run: |
          echo "Checking Postman collections for hardcoded URLs..."
          for collection in ./*postman_collection.json; do
            if grep -E '"url":\s*"https?://[^"]+' "$collection"; then
              echo "Hardcoded URL found in $collection"
              exit 1
            else
              echo "$collection uses variables"
            fi
          done
      - name: Run All Postman Collections
        run: |
          set -e  # stop if any command fails
          for collection in ./*postman_collection.json; do
            echo "Running $collection ..."
            newman run "$collection" \
              --env-var rpc_url=${{ secrets.BASE_URL }} \
              --reporters cli,junit \
              --reporter-junit-export "newman-results-$(basename $collection .json).xml"
          done
